version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ./node_modules/.bin/nodemon --watch "./src" -x "node --experimental-modules" src/index.mjs
    image: contact
    environment:
    - MAILGUN_KEY=blah
    - MAILGUN_DOMAIN=blah
    - SEND_TO=me@email.com
    - REDIRECT_URL=
    ports:
      - 3000:80
    volumes:
      - ./src:/src